development:
  adapter: postgresql
  encoding: unicode
  database: sfd
  pool: 5
  username: postgres
  password: helloworld

test:
  adapter: postgresql
  encoding: unicode
  database: sfd
  pool: 5
  username: postgres
  password: helloworld

production:
  adapter: postgresql
  encoding: unicode
  database: sfd
  pool: 5
  username: postgres
  password: helloworld